### ISSUE TITLE
/results is broken

### ISSUE THREAD

**Issue by simeg** [simeg/hltv-api#32]
Because of an update to HLTV's result page the /result endpoint is broken and returning 500:

```
Nov 08 16:12:26 hltv-api app/web.1: Traceback (most recent call last): 
Nov 08 16:12:26 hltv-api app/web.1:   File "/src/results.py", line 45, in _parse_results 
Nov 08 16:12:26 hltv-api app/web.1:     date = get_text(date) 
Nov 08 16:12:26 hltv-api app/web.1:   File "/src/utils.py", line 61, in get_text 
Nov 08 16:12:26 hltv-api app/web.1:     return element.get_text() 
Nov 08 16:12:26 hltv-api app/web.1: AttributeError: 'NoneType' object has no attribute 'get_text
```

**Comment by simeg** [comment]
Fixed in cbe9ff96fcf1c83ca64af20cc968102f40588be8.
